use_frameworks!

target 'ScreenCapturer_Example' do
  pod 'ScreenCapturer', :path => '../'

  target 'ScreenCapturer_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
